config/routes.rb
Rails.application.routes.draw do
  root 'purchase_orders#index'
  resources :order_items
  resources :items
  resources :purchase_orders
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/item.rb
class Item < ApplicationRecord
end

app/models/order_item.rb
class OrderItem < ApplicationRecord
  belongs_to :purchase_order
  belongs_to :item
end

app/models/purchase_order.rb
class PurchaseOrder < ApplicationRecord
	has_many :order_items, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  before_action :set_item, only: %i[ show edit update destroy ]

  # GET /items or /items.json
  def index
    @items = Item.all
  end

  # GET /items/1 or /items/1.json
  def show
  end

  # GET /items/new
  def new
    @item = Item.new
  end

  # GET /items/1/edit
  def edit
  end

  # POST /items or /items.json
  def create
    @item = Item.new(item_params)

    respond_to do |format|
      if @item.save
        format.html { redirect_to @item, notice: "Item was successfully created." }
        format.json { render :show, status: :created, location: @item }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @item.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /items/1 or /items/1.json
  def update
    respond_to do |format|
      if @item.update(item_params)
        format.html { redirect_to @item, notice: "Item was successfully updated." }
        format.json { render :show, status: :ok, location: @item }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @item.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /items/1 or /items/1.json
  def destroy
    @item.destroy!

    respond_to do |format|
      format.html { redirect_to items_path, status: :see_other, notice: "Item was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_item
      @item = Item.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def item_params
      params.require(:item).permit(:sku, :title, :nickname, :price, :inventory, :fullfillment_fee, :unit_cost)
    end
end

app/controllers/order_items_controller.rb
class OrderItemsController < ApplicationController
end

app/controllers/purchase_orders_controller.rb
class PurchaseOrdersController < ApplicationController
  before_action :set_purchase_order, only: %i[ show edit update destroy ]

  # GET /purchase_orders or /purchase_orders.json
  def index
    @purchase_orders = PurchaseOrder.all
  end

  # GET /purchase_orders/1 or /purchase_orders/1.json
  def show
  end

  # GET /purchase_orders/new
  def new
    @purchase_order = PurchaseOrder.new
  end

  # GET /purchase_orders/1/edit
  def edit
  end

  # POST /purchase_orders or /purchase_orders.json
  def create
    @purchase_order = PurchaseOrder.new(purchase_order_params)

    respond_to do |format|
      if @purchase_order.save
        format.html { redirect_to @purchase_order, notice: "Purchase order was successfully created." }
        format.json { render :show, status: :created, location: @purchase_order }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @purchase_order.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /purchase_orders/1 or /purchase_orders/1.json
  def update
    respond_to do |format|
      if @purchase_order.update(purchase_order_params)
        format.html { redirect_to @purchase_order, notice: "Purchase order was successfully updated." }
        format.json { render :show, status: :ok, location: @purchase_order }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @purchase_order.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /purchase_orders/1 or /purchase_orders/1.json
  def destroy
    @purchase_order.destroy!

    respond_to do |format|
      format.html { redirect_to purchase_orders_path, status: :see_other, notice: "Purchase order was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_purchase_order
      @purchase_order = PurchaseOrder.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def purchase_order_params
      params.require(:purchase_order).permit(:order_num, :purchase_date, :status, :sales_channel, :order_total, :num_items_shipped, :num_items_unshipped, :payment_method, :shipped_at, :shipping_price, :shipping_tax, :carrier, :tracking_number, :estimated_arrival_date, :fullfillment_center, :confirmed_at, :returned_date, :return_reason, :notes, :returned_at, :ship_to_name, :ship_to_address)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/order_items_helper.rb
module OrderItemsHelper
end

app/helpers/purchase_orders_helper.rb
module PurchaseOrdersHelper
end

app/views/items/_form.html.erb
<%= form_with(model: item) do |form| %>
  <% if item.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(item.errors.count, "error") %> prohibited this item from being saved:</h2>

      <ul>
        <% item.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :sku, style: "display: block" %>
    <%= form.text_field :sku %>
  </div>

  <div>
    <%= form.label :title, style: "display: block" %>
    <%= form.text_field :title %>
  </div>

  <div>
    <%= form.label :nickname, style: "display: block" %>
    <%= form.text_field :nickname %>
  </div>

  <div>
    <%= form.label :price, style: "display: block" %>
    <%= form.text_field :price %>
  </div>

  <div>
    <%= form.label :inventory, style: "display: block" %>
    <%= form.number_field :inventory %>
  </div>

  <div>
    <%= form.label :fullfillment_fee, style: "display: block" %>
    <%= form.text_field :fullfillment_fee %>
  </div>

  <div>
    <%= form.label :unit_cost, style: "display: block" %>
    <%= form.text_field :unit_cost %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/items/_item.html.erb
<div id="<%= dom_id item %>">
  <p>
    <strong>Sku:</strong>
    <%= item.sku %>
  </p>

  <p>
    <strong>Title:</strong>
    <%= item.title %>
  </p>

  <p>
    <strong>Nickname:</strong>
    <%= item.nickname %>
  </p>

  <p>
    <strong>Price:</strong>
    <%= item.price %>
  </p>

  <p>
    <strong>Inventory:</strong>
    <%= item.inventory %>
  </p>

  <p>
    <strong>Fullfillment fee:</strong>
    <%= item.fullfillment_fee %>
  </p>

  <p>
    <strong>Unit cost:</strong>
    <%= item.unit_cost %>
  </p>

</div>

app/views/items/edit.html.erb
<h1>Editing item</h1>

<%= render "form", item: @item %>

<br>

<div>
  <%= link_to "Show this item", @item %> |
  <%= link_to "Back to items", items_path %>
</div>

app/views/items/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Items</h1>

<div id="items">
  <% @items.each do |item| %>
    <%= render item %>
    <p>
      <%= link_to "Show this item", item %>
    </p>
  <% end %>
</div>

<%= link_to "New item", new_item_path %>

app/views/items/new.html.erb
<h1>New item</h1>

<%= render "form", item: @item %>

<br>

<div>
  <%= link_to "Back to items", items_path %>
</div>

app/views/items/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @item %>

<div>
  <%= link_to "Edit this item", edit_item_path(@item) %> |
  <%= link_to "Back to items", items_path %>

  <%= button_to "Destroy this item", @item, method: :delete %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Elasticapp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/purchase_orders/_form.html.erb
<%= form_with(model: purchase_order) do |form| %>
  <% if purchase_order.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(purchase_order.errors.count, "error") %> prohibited this purchase_order from being saved:</h2>

      <ul>
        <% purchase_order.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :order_num, style: "display: block" %>
    <%= form.text_field :order_num %>
  </div>

  <div>
    <%= form.label :purchase_date, style: "display: block" %>
    <%= form.datetime_field :purchase_date %>
  </div>

  <div>
    <%= form.label :status, style: "display: block" %>
    <%= form.text_field :status %>
  </div>

  <div>
    <%= form.label :sales_channel, style: "display: block" %>
    <%= form.text_field :sales_channel %>
  </div>

  <div>
    <%= form.label :order_total, style: "display: block" %>
    <%= form.text_field :order_total %>
  </div>

  <div>
    <%= form.label :num_items_shipped, style: "display: block" %>
    <%= form.number_field :num_items_shipped %>
  </div>

  <div>
    <%= form.label :num_items_unshipped, style: "display: block" %>
    <%= form.number_field :num_items_unshipped %>
  </div>

  <div>
    <%= form.label :payment_method, style: "display: block" %>
    <%= form.text_field :payment_method %>
  </div>

  <div>
    <%= form.label :shipped_at, style: "display: block" %>
    <%= form.datetime_field :shipped_at %>
  </div>

  <div>
    <%= form.label :shipping_price, style: "display: block" %>
    <%= form.text_field :shipping_price %>
  </div>

  <div>
    <%= form.label :shipping_tax, style: "display: block" %>
    <%= form.text_field :shipping_tax %>
  </div>

  <div>
    <%= form.label :carrier, style: "display: block" %>
    <%= form.text_field :carrier %>
  </div>

  <div>
    <%= form.label :tracking_number, style: "display: block" %>
    <%= form.text_field :tracking_number %>
  </div>

  <div>
    <%= form.label :estimated_arrival_date, style: "display: block" %>
    <%= form.datetime_field :estimated_arrival_date %>
  </div>

  <div>
    <%= form.label :fullfillment_center, style: "display: block" %>
    <%= form.text_field :fullfillment_center %>
  </div>

  <div>
    <%= form.label :confirmed_at, style: "display: block" %>
    <%= form.datetime_field :confirmed_at %>
  </div>

  <div>
    <%= form.label :returned_date, style: "display: block" %>
    <%= form.datetime_field :returned_date %>
  </div>

  <div>
    <%= form.label :return_reason, style: "display: block" %>
    <%= form.text_field :return_reason %>
  </div>

  <div>
    <%= form.label :notes, style: "display: block" %>
    <%= form.text_area :notes %>
  </div>

  <div>
    <%= form.label :returned_at, style: "display: block" %>
    <%= form.datetime_field :returned_at %>
  </div>

  <div>
    <%= form.label :ship_to_name, style: "display: block" %>
    <%= form.text_field :ship_to_name %>
  </div>

  <div>
    <%= form.label :ship_to_address, style: "display: block" %>
    <%= form.text_field :ship_to_address %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/purchase_orders/_purchase_order.html.erb
<div id="<%= dom_id purchase_order %>">
  <p>
    <strong>Order num:</strong>
    <%= purchase_order.order_num %>
  </p>

  <p>
    <strong>Purchase date:</strong>
    <%= purchase_order.purchase_date %>
  </p>

  <p>
    <strong>Status:</strong>
    <%= purchase_order.status %>
  </p>

  <p>
    <strong>Sales channel:</strong>
    <%= purchase_order.sales_channel %>
  </p>

  <p>
    <strong>Order total:</strong>
    <%= purchase_order.order_total %>
  </p>

  <p>
    <strong>Num items shipped:</strong>
    <%= purchase_order.num_items_shipped %>
  </p>

  <p>
    <strong>Num items unshipped:</strong>
    <%= purchase_order.num_items_unshipped %>
  </p>

  <p>
    <strong>Payment method:</strong>
    <%= purchase_order.payment_method %>
  </p>

  <p>
    <strong>Shipped at:</strong>
    <%= purchase_order.shipped_at %>
  </p>

  <p>
    <strong>Shipping price:</strong>
    <%= purchase_order.shipping_price %>
  </p>

  <p>
    <strong>Shipping tax:</strong>
    <%= purchase_order.shipping_tax %>
  </p>

  <p>
    <strong>Carrier:</strong>
    <%= purchase_order.carrier %>
  </p>

  <p>
    <strong>Tracking number:</strong>
    <%= purchase_order.tracking_number %>
  </p>

  <p>
    <strong>Estimated arrival date:</strong>
    <%= purchase_order.estimated_arrival_date %>
  </p>

  <p>
    <strong>Fullfillment center:</strong>
    <%= purchase_order.fullfillment_center %>
  </p>

  <p>
    <strong>Confirmed at:</strong>
    <%= purchase_order.confirmed_at %>
  </p>

  <p>
    <strong>Returned date:</strong>
    <%= purchase_order.returned_date %>
  </p>

  <p>
    <strong>Return reason:</strong>
    <%= purchase_order.return_reason %>
  </p>

  <p>
    <strong>Notes:</strong>
    <%= purchase_order.notes %>
  </p>

  <p>
    <strong>Returned at:</strong>
    <%= purchase_order.returned_at %>
  </p>

  <p>
    <strong>Ship to name:</strong>
    <%= purchase_order.ship_to_name %>
  </p>

  <p>
    <strong>Ship to address:</strong>
    <%= purchase_order.ship_to_address %>
  </p>

</div>

app/views/purchase_orders/edit.html.erb
<h1>Editing purchase order</h1>

<%= render "form", purchase_order: @purchase_order %>

<br>

<div>
  <%= link_to "Show this purchase order", @purchase_order %> |
  <%= link_to "Back to purchase orders", purchase_orders_path %>
</div>

app/views/purchase_orders/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Purchase orders</h1>

<div id="purchase_orders">
  <% @purchase_orders.each do |purchase_order| %>
    <%= render purchase_order %>
    <p>
      <%= link_to "Show this purchase order", purchase_order %>
    </p>
  <% end %>
</div>

<%= link_to "New purchase order", new_purchase_order_path %>

app/views/purchase_orders/new.html.erb
<h1>New purchase order</h1>

<%= render "form", purchase_order: @purchase_order %>

<br>

<div>
  <%= link_to "Back to purchase orders", purchase_orders_path %>
</div>

app/views/purchase_orders/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @purchase_order %>

<div>
  <%= link_to "Edit this purchase order", edit_purchase_order_path(@purchase_order) %> |
  <%= link_to "Back to purchase orders", purchase_orders_path %>

  <%= button_to "Destroy this purchase order", @purchase_order, method: :delete %>
</div>